EXE = 
LIB = libhub-app.a

INC_DIRS =  $(APP_DIR)/include \
			$(ZLOG_DIR)/include \
			$(UTILS_DIR)/include \
			$(JSONC_DIR)/include \
			$(MQTTC_DIR)/include \
			$(TOMCRYPT_DIR)/src/headers \
			$(CIPHER_DIR)/include \
			$(HTTPD_DIR)/include \
			$(SHARE_DIR)/include

LINK_LIBS = 

include $(ROOT_DIR)/make/make.rule
