EXE = 
LIB = libcipher.a
DLL = 

INC_DIRS = ../include \
           $(SHARE_LIBS_DIR)/utils/include \
           $(SHARE_LIBS_DIR)/share/include \
           $(SHARE_LIBS_DIR)/libtomcrypt-1.17/src/headers

LINK_LIBS = 

include $(ROOT_DIR)/make/make.rule