EXE       = mqttmsghub.exe
LIB       = 

INC_DIRS  = $(APP_DIR)/include

LINK_LIBS += hub-app cipher tomcrypt utils zlog json-c mqtt-c httpd 
LINK_LIBS += pthread rt

include $(ROOT_DIR)/make/make.rule